### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by TebaldiMaster** [Drutol/MALClient#255]
### System

* MALClient Version: 1.4.15.0
* Platform: Android 8 / MIUI 10.2

### Description

I had consecutive crashes after browsing through MAL for more than a minute, like visiting profiles or checking my friend's list... And once it crashed while I clicked on notification button. It also crashes every time I put it on background... 

Crash report log transcription of one of these:

android.runtime.JavaProxyThrowable: System.Net.Http.HttpRequestException: timeout ---> Java.IO.IOException: timeout
  at ModernHttpClient.NativeMessageHandler+<SendAsync>d__24.MoveNext () [0x0048a] in <35e0993c504d41f3a6e961d0d9bf5c5d>:0 
   --- End of inner exception stack trace ---
  at ModernHttpClient.NativeMessageHandler+<SendAsync>d__24.MoveNext () [0x0053a] in <35e0993c504d41f3a6e961d0d9bf5c5d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Net.Http.HttpClient+<SendAsyncWorker>d__49.MoveNext () [0x000ca] in <26a8b460d12f4ed0bdfda76b8c5d186d>:0 
--- End of stack trace from previous location where exception was thrown ---
  at MALClient.XShared.Comm.Profile.ProfileQuery+<GetComments>d__3.MoveNext () [0x00106] in <5a6a8461c4b44f61beeaea2d8ecd052f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at MALClient.XShared.Comm.Profile.ProfileDataHelper+<UpdateComments>d__0.MoveNext () [0x0007c] in <5a6a8461c4b44f61beeaea2d8ecd052f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at MALClient.XShared.ViewModels.Main.ProfilePageViewModel+<<get_RefreshCommentsCommand>b__64_0>d.MoveNext () [0x00082] in <5a6a8461c4b44f61beeaea2d8ecd052f>:0 
--- End of stack trace from previous location where exception was thrown ---
  at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) [0x00000] in <21f1364161d645d0a18540817c93c168>:0 
  at Android.App.SyncContext+<>c__DisplayClass2_0.<Post>b__0 () [0x00000] in <6337a86ada624255912b1818d76e477f>:0 
  at Java.Lang.Thread+RunnableImplementor.Run () [0x00008] in <6337a86ada624255912b1818d76e477f>:0 
  at Java.Lang.IRunnableInvoker.n_Run (System.IntPtr jnienv, System.IntPtr native__this) [0x00009] in <6337a86ada624255912b1818d76e477f>:0 
  at (wrapper dynamic-method) System.Object.4(intptr,intptr)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:30)
	at android.os.Handler.handleCallback(Handler.java:794)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:176)
	at android.app.ActivityThread.main(ActivityThread.java:6635)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by TebaldiMaster** [comment]
I was on a bus at moment, so maybe it was the Internet access, but it's still annoying to have the app crashing every time your connection oscillates.

**Comment by Drutol** [comment]
Hello. Hmm, I've done some stuff around this lately in v1.5.0.3. Any better?

**Comment by TebaldiMaster** [comment]
I have to test. Soon enough I'll give you a reply.

**Comment by Drutol** [comment]
@mateustebaldi Nice avatar btw, the daki with this design is on its way to me xd
